mdbook: Add linkcheck backend
Adds the mdbook-linkcheck backend to check for broken links.

https://github.com/Michael-F-Bryan/mdbook-linkcheck

- mdbook-linkcheck added to rust-toolchain.toml
- Configuration is added to book.toml
- A few cases where square brackets were not escaped in md files
  are fixed
- publish-mdbook.yml is updated to upload artifacts from docs/book/html
  instead of docs/book because when mdbook has multiple output backends
  ([output.html] and [output.linkcheck]), it nests output in
  subdirectories under the build dir (e.g., book/html/, book/linkcheck/)
  instead of writing directly to book/.

Since mdbook-linkcheck can run after these changes without warnings,
it is not marked as optional in the book.toml configuration and it is
installed in the CI workflow, so it can run like the other mdbook
tools.

A broken link will fail `mdbook build`, with a clear error message
about which link is broken:

  ```
  (mdbook::renderer): Invoking the "linkcheck" renderer
  error: File not found: todo!()
      ┌─ introduction.md:118:4
      │
  118 │ 4. [Contributing to Patina](todo!())
      │    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File not found: todo!()

  error: File not found: ../does_not_exist.md
    ┌─ dev/documenting/reference.md:15:1
    │
  15 │ [Test Broken Link](../does_not_exist.md)
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File not found: ../does_not_exist.md

  Error: One or more incorrect links
  ```

Note: The `follow-web-links` default option is left to its default
value of `false` to avoid linkcheck attempting to validate external
links and potentially causing CI failures due to external sites being
down or rate-limiting requests.

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>