sdk: Gate c_ptr and status_code
sdk/patina/src/lib.rs gates the alloc crate:

```
cfg_attr(any(test, feature = "alloc"), feature(allocator_api))
```

Code in sdk/patina/src/base/c_ptr.rs was using `alloc::boxed::Box`
without applying a similar gate. This change applies the gate on
usage there so the crate can be built without the alloc feature.

A similar fix in the sdk is made in status_code.rs. When built with
`cargo hack check --workspace --no-default-features` the following
error was seen:

```
error[E0599]: no method named `concat` found for array `[&[u8]; 2]` in the current scope
    let mut data_buffer = [any_as_u8_slice(&header), any_as_u8_slice(&data)].concat();
```

`[T]::concat()` on an array of slices returns `Vec<u8>` with alloc's
`Concat` trait.

Three changes were made for this:

1. Splitting the import block, so `use core::{mem, ptr, slice}` so
   `mem` and `slice` are gated on `alloc`.
2. Updating `pub fn report_status_code_with_data<T>` to be gated on
   the `alloc` feature.
3. Updating `fn any_as_u8_slice<T: Sized>(p: &T) -> &[u8]` to be
   gated on the `alloc` feature as well to avoid a dead code warning
   since it was only called by `report_status_code_with_data<T>`.

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>